Arithmetic tasks
AndrejsBoja/C-basics pull request #3
Opened 2021-04-07 08:28 UTC by AndrejsBoja

2021-04-07 18:16 UTC, ausmoons requested changes
Pārskati visos failos {} un tukšās rindas

2021-04-07 18:16 UTC, ausmoons commented on Arithmetic/CalculateArea/Program.cs
> +            if (radius < 0)
Un ja ir 0?

2021-04-07 18:16 UTC, ausmoons commented on TypesAndVariables/SadFor/Program.cs
> +            //fixme so I would compile
?

2021-04-07 18:16 UTC, ausmoons commented on TypesAndVariables/VariablesAndNames/Program.cs
> +            //cars_not_driven  // free cars
?

2021-04-07 18:54 UTC, AndrejsBoja commented on Arithmetic/CalculateArea/Program.cs
> +            if (radius < 0)
Ergļa acs tev :)

2021-04-07 18:55 UTC, AndrejsBoja commented on Arithmetic/CalculateArea/Program.cs
> +            if (radius < 0)
Līva , ja es jau mergoju šo pull request, es varu izmainīt lokāli un comitu uztaisīt ? vai labāk jau šeit githuba salabot kodu ?

2021-04-08 18:25 UTC, ausmoons commented on Arithmetic/CalculateArea/Program.cs
> +            if (radius < 0)
Ko tu domā, ka jau mergoji? Tev pašlaik ir tikai PR. Jap, tieši lokāli ir jāmaina un tad jātaisa commit & push

2021-04-08 18:28 UTC, ausmoons approved these changes

2021-04-08 18:28 UTC, ausmoons commented on Arithmetic/CalculateArea/Program.cs
> +            if ( length < 0 || width < 0 )
Šeit arī..

2021-04-09 17:08 UTC, merged